function [rotM] = eul2rotmc(eul)

    zturn = [cos(eul(1)), -sin(eul(1)), 0; ...
        sin(eul(1)), cos(eul(1)), 0; ...
        0, 0, 1];
   
    yturn = [cos(eul(2)),0, sin(eul(2)); ...
        0, 1, 0; ...
        -sin(eul(2)), 0 ,cos(eul(2))];
    
    xturn = [1, 0, 0; ...
        0 cos(eul(3)), -sin(eul(3)); ...
        0 sin(eul(3)), cos(eul(3))];

    rotM = zturn*yturn*xturn;
end